server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: client-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**
        - id: bankaccounts-microservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**

        - id: bankdeposit-microservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/deposit/**
        - id: bankwithdrawal-microservice
          uri: http://localhost:8084
          predicates:
            - Path=/api/withdrawal/**
        - id: bankcredit-microservice
          uri: http://localhost:8085
          predicates:
            - Path=/api/credit/**