server:
  port: 8097

spring:
  application:
    name: bankcommission-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?retryWrites=true&w=majority
      #uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/creditcard?retryWrites=true&w=majority
      uri: mongodb+srv://julio:julio@bootcamp.drivb.mongodb.net/commission?retryWrites=true&w=majority

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true

info:
  application:
    name : bankcommission-microservice
    Description : This is a Microservice to manage commission
    artifact : bank-commission
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka

apiclient:
  uri: http://localhost:8083
microservice-client:
  uri: /api/clients/
microservice-accounts:
  uri: /api/accounts/