server:
  port: 8094
spring:
  application:
    name: bankwithdrawal-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/withdrawal?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/withdrawal?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka

info:
  application:
    name : bankdeposit-microservice
    Description : This is a Microservice to manage deposits
    artifact : bank-clients
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4
