server:
  port: 8092
spring:
  application:
    name: bankaccounts-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/accounts?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/accounts?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka

info:
  application:
    name : client-microservice
    Description : This is a Microservice to manage clients
    artifact : bank-clients
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4

apiclient:
  uri: http://localhost:8095
microservice-clients:
  uri: /api/clients/
microservice-accounts:
  uri: /api/accounts/







