server:
  port: 8093
spring:
  application:
    name: bankdeposit-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/deposit?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/deposit?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
info:
  application:
    name : bankdeposit-microservice
    Description : This is a Microservice to manage clients
    artifact : bank-clients
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4


apiclient:
  uri: http://localhost:8083
microservice-client:
  uri: /api/clients/
microservice-accounts:
  uri: /api/accounts/
