server:
  port: 8086

spring:
  application:
    name: creditcard-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/clients?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
